# Generated by Django 4.1.5 on 2023-02-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_shoes_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('descrtiption', models.TextField()),
                ('what_a_clothes', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='media/image')),
            ],
        ),
        migrations.AlterField(
            model_name='shoes',
            name='description',
            field=models.TextField(),
        ),
    ]
