# Generated by Django 4.1.5 on 2023-02-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_wardrobe_alter_shoes_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wardrobe',
            old_name='descrtiption',
            new_name='w_descrtiption',
        ),
    ]
