# Generated by Django 4.1.5 on 2023-01-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='register_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
